// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjffvisskyvdgnwwmkhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZmZ2aXNza3l2ZGdud3dta2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTk4OTMsImV4cCI6MjA2NzM5NTg5M30.bRl9xmZMm_Y7Txt-Kp70oP-hT5l_PAediV8WWVhYGxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
